Nass errors on nass page 186329
DFE-Digital/check-your-eligibility-frontend pull request #250
Opened 2024-11-05 10:52 UTC by HarrisonShawAdvania

Errors that should be on the Nass Page are now shown on the Nass page instead of sending the user back to Enter_Details page

2024-11-05 10:56 UTC, marten-wetterberg requested changes
Is there any chance we could get a unit/cypress test to cover this as a regression test?

2024-11-05 10:57 UTC, HarrisonShawAdvania commented
@marten-wetterberg I can work on some unit tests and work with Sam on cypress tests.

2024-11-06 13:20 UTC, HarrisonShawAdvania commented
@marten-wetterberg cypress tests added to cover the new error messages

2024-11-06 13:36 UTC, samfallowfield commented on tests/cypress/support/commands.ts
This doesn't need to be broken out into a separate function, only has one current use and will need to be changed after upcoming refactor

2024-11-07 10:52 UTC, marten-wetterberg approved these changes

2024-11-07 11:17 UTC, merged