addition of qualtrics survey into the admin side of the journey
DFE-Digital/check-your-eligibility-frontend pull request #282
Opened 2024-12-05 15:29 UTC by HarrisonShawAdvania

2024-12-05 15:30 UTC, HarrisonShawAdvania commented
done in relation to https://dfe-gov-uk.visualstudio.com/Solutions%20Development/_boards/board/t/ECS/Stories/?workitem=159384

2024-12-05 15:52 UTC, marten-wetterberg requested changes

2024-12-05 15:53 UTC, HarrisonShawAdvania commented on CheckYourEligibility-Admin/Views/Shared/_Layout.cshtml
> +                    This is a new service - your <a class="govuk-link" href="https://dferesearch.fra1.qualtrics.com/jfe/form/SV_bjB0MQiSJtvhyZw">feedback</a> will help us to improve it.
yeah of course

2024-12-05 16:13 UTC, marten-wetterberg approved these changes

2024-12-06 09:45 UTC, marten-wetterberg approved these changes

2024-12-06 09:45 UTC, merged